package com.twig.app

/**
 * The one line of shell startup that makes a terminal session say **where it is**.
 *
 * Android's `/system/bin/sh` (mksh) writes no terminal title of its own, and neither does anything else
 * installed on a stock device, so a local session had nothing to show under its name in the session list
 * while SSH sessions — where htop, vim or a distribution's prompt write one — did. What this promises is
 * the **working directory**, nothing more: mksh re-expands PS1 on every prompt, so it follows `cd`.
 *
 * ★ The `\001 … \001` wrapper is not decoration. mksh counts the prompt's width in characters, escape
 * sequences included, and a prompt it believes is wider than it is misplaces the cursor while editing a
 * long command line. ksh's convention — which Android's mksh implements — is *if the second character of
 * PS1 is `\r`, the first character is a delimiter and anything between a pair of it is not counted*.
 * Measured on a device at 40 columns with a 3-character prompt, counting the characters echoed before the
 * line wrapped: bare escape 27, wrapped 35, a plain prompt with no escape at all 35.
 *
 * Lives here rather than in the terminal UI because the Shizuku helper ([com.twig.app.priv.TwigPrivService],
 * a different process) has to write the same thing for privileged shells.
 */
object TermRc {

    /** Appended to an rc file that already set PS1 — it wraps whatever prompt is there. */
    const val TITLE =
        "# Report the working directory as the terminal title (OSC 0); Twig's session\n" +
            "# list shows it under the session name. PS1 is re-expanded every prompt, so\n" +
            "# this follows cd.\n" +
            "# The \\001 … \\001 wrapper keeps mksh from counting the escape as prompt width\n" +
            "# (without it the cursor drifts when editing a long command line).\n" +
            "PS1=\$'\\001\\r\\001\\033]0;\${PWD}\\a\\001'\"\$PS1\"\n"

    /**
     * Where the rc for **privileged** shells lives. It cannot be the app's own `.mkshrc`: the Shizuku helper
     * runs as the shell uid, and the app's private directory is 0700 — unreadable to it. `/data/local/tmp/twig`
     * is the directory the helper already owns (it extracts `libtwigpty.so` there), and shell and root can
     * both read it.
     */
    const val PRIV_PATH = "/data/local/tmp/twig/mkshrc"

    /**
     * Setting `$ENV` **replaces** mksh's default startup file, so the system rc has to be sourced explicitly —
     * without that line a privileged session would lose the `host:/path #` prompt it has today.
     */
    const val PRIV_CONTENT = "# Generated by Twig for privileged shell sessions.\n" +
        "[ -f /system/etc/mkshrc ] && . /system/etc/mkshrc\n" +
        "\n" + TITLE
}
