package com.twig.app

/**
 * The one line of shell startup that makes a terminal session say **where it is**.
 *
 * Android's `/system/bin/sh` (mksh) writes no terminal title of its own, and neither does anything else
 * installed on a stock device, so a local session had nothing to show under its name in the session list
 * while SSH sessions — where htop, vim or a distribution's prompt write one — did. What this promises is
 * the **working directory**, nothing more: mksh re-expands PS1 on every prompt, so it follows `cd`.
 *
 * ★ The `\001 … \001` wrapper is not decoration. mksh counts the prompt's width in characters, escape
 * sequences included, and a prompt it believes is wider than it is misplaces the cursor while editing a
 * long command line. ksh's convention — which Android's mksh implements — is *if the second character of
 * PS1 is `\r`, the first character is a delimiter and anything between a pair of it is not counted*.
 * Measured on a device at 40 columns with a 3-character prompt, counting the characters echoed before the
 * line wrapped: bare escape 27, wrapped 35, a plain prompt with no escape at all 35.
 *
 * Lives here rather than in the terminal UI because the Shizuku helper ([com.twig.app.priv.TwigPrivService],
 * a different process) has to write the same thing for privileged shells.
 */
object TermRc {

    /** Appended to an rc file that already set PS1 — it wraps whatever prompt is there. */
    const val TITLE =
        "# Report the working directory as the terminal title (OSC 0); Twig's session\n" +
            "# list shows it under the session name. PS1 is re-expanded every prompt, so\n" +
            "# this follows cd.\n" +
            "# The \\001 … \\001 wrapper keeps mksh from counting the escape as prompt width\n" +
            "# (without it the cursor drifts when editing a long command line).\n" +
            "PS1=\$'\\001\\r\\001\\033]0;\${PWD}\\a\\001'\"\$PS1\"\n"

    /**
     * The one line an SSH session is opened with, so the shell on the far side reports its working
     * directory as the terminal title too.
     *
     * It cannot be done the local way — that edits a file, and the file over there is the user's.
     * It is worth doing because a remote prompt's own title is written for humans and can be
     * **truncated** (`..ork/self/twig`, zsh's `%<..<`), and half a path cannot be turned back into a
     * directory; the far side therefore gets a prompt hook of our own, for the session only,
     * appended after whatever it already had so that ours is the title that survives.
     *
     * ★ It is sent **only chained onto the `cd` a session opens with**, never on its own: that line
     * ends in `clear`, so it costs nothing to look at, while on its own it is a screenful of shell
     * syntax echoed into someone else's session (zsh's line editor redraws it, so it even appears
     * twice). Clearing that away would take the login banner with it, so the answer is not to send
     * it. A session that never gets the hook is not broken — it falls back to the title the remote
     * prompt writes, which is also how [com.twig.app.ui.TermSession.pathTitle] gets its material.
     *
     * Measured through a real pty on both shells before shipping: with a distribution's default
     * bash prompt the system's own `user@host:/tmp` is emitted first and ours (`/tmp`) last, which
     * is the one that sticks; under zsh only ours appears. Other shells run the `if` and match no
     * branch, so nothing happens and nothing breaks — and the whole line is POSIX, so a `cd` chained
     * in front of it still short-circuits on failure.
     *
     * bash embeds it in PS1 rather than PROMPT_COMMAND on purpose: a PS1 that sets its own title
     * (Debian and Ubuntu ship one) is printed *after* PROMPT_COMMAND runs and would overwrite ours.
     * zsh uses `precmd_functions` for the same reason, appended last.
     */
    const val REMOTE_TITLE =
        "if [ -n \"\$ZSH_VERSION\" ]; then _twig_title(){ printf '\\033]0;%s\\a' \"\$PWD\"; }; " +
            "precmd_functions+=(_twig_title); elif [ -n \"\$BASH_VERSION\" ]; then " +
            "PS1=\"\$PS1\"'\\[\\e]0;\$PWD\\a\\]'; fi"

    /**
     * Where the rc for **privileged** shells lives. It cannot be the app's own `.mkshrc`: the Shizuku helper
     * runs as the shell uid, and the app's private directory is 0700 — unreadable to it. `/data/local/tmp/twig`
     * is the directory the helper already owns (it extracts `libtwigpty.so` there), and shell and root can
     * both read it.
     */
    const val PRIV_PATH = "/data/local/tmp/twig/mkshrc"

    /**
     * Setting `$ENV` **replaces** mksh's default startup file, so the system rc has to be sourced explicitly —
     * without that line a privileged session would lose the `host:/path #` prompt it has today.
     */
    const val PRIV_CONTENT = "# Generated by Twig for privileged shell sessions.\n" +
        "[ -f /system/etc/mkshrc ] && . /system/etc/mkshrc\n" +
        "\n" + TITLE
}
